Config:
  manutencao-ativada: '&6&l[AVISO] &fA manutenção foi ativada, todos os jogadores serão expulsos.'
  manutencao-desativada: '&6&l[AVISO] &fA manutenção foi desativada.'
  mensagem-kick: '&c&lREDE NETWORK %nl% &cPrecisamos resolver algumas coisas, voltamos já!'
  MOTD: '&6&lREDE NETWORK %nl% &eEstamos em &cmanutenção&e, voltamos já!'

Msg-erro:
  manutencao-ativada: '&cA manutenção já está ativada.'
  manutencao-desativada: '&cA manutenção já está desativada.'